server:
  port: 8080

jwt:
  secret_key : tGmM2qNIej
  time_expiration : 86400000


spring:
  application:
    name: manage_student
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manage_student?characterEncoding=utf8&connectionCollation=utf8mb4_bin&sslMode=DISABLED&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 1005
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jpa:
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        globally_quoted_identifiers: true
  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER
upload:
  file:
    path : D:\Learning\DoAnTotNghiep\ManageStudent

mail:
  username: "dieplinh1005.dh@gmail.com"
  password: "gubn ytpl xcuq jcoj"
