// API get all class by subjectId
export const GET_CLASSES_IN_SUBJECT_REQUEST = 'GET_CLASSES_IN_SUBJECT_REQUEST';
export const GET_CLASSES_IN_SUBJECT_SUCCESS = 'GET_CLASSES_IN_SUBJECT_SUCCESS';
export const GET_CLASSES_IN_SUBJECT_FAILURE = 'GET_CLASSES_IN_SUBJECT_FAILURE';

// API get all class
export const GET_ALL_CLASSES_REQUEST = 'GET_ALL_CLASSES_REQUEST';
export const GET_ALL_CLASSES_SUCCESS = 'GET_ALL_CLASSES_SUCCESS';
export const GET_ALL_CLASSES_FAILURE = 'GET_ALL_CLASSES_FAILURE';

// API create class in subject
export const CREATE_CLASS_IN_SUBJECT_REQUEST = 'CREATE_CLASS_IN_SUBJECT_REQUEST';
export const CREATE_CLASS_IN_SUBJECT_SUCCESS = 'CREATE_CLASS_IN_SUBJECT_SUCCESS';
export const CREATE_CLASS_IN_SUBJECT_FAILURE = 'CREATE_CLASS_IN_SUBJECT_FAILURE';

// API edit class in subject
export const EDIT_CLASS_IN_SUBJECT_REQUEST = 'EDIT_CLASS_IN_SUBJECT_REQUEST';
export const EDIT_CLASS_IN_SUBJECT_SUCCESS = 'EDIT_CLASS_IN_SUBJECT_SUCCESS';
export const EDIT_CLASS_IN_SUBJECT_FAILURE = 'EDIT_CLASS_IN_SUBJECT_FAILURE';

// Get list teacher
export const GET_LIST_TEACHER_REQUEST = 'GET_LIST_TEACHER_REQUEST';
export const GET_LIST_TEACHER_SUCCESS = 'GET_LIST_TEACHER_SUCCESS';
export const GET_LIST_TEACHER_FAILURE = 'GET_LIST_TEACHER_FAILURE';

// Get list class by course id
export const GET_CLASSES_BY_COURSE_REQUEST = 'GET_CLASSES_BY_COURSE_REQUEST';
export const GET_CLASSES_BY_COURSE_SUCCESS = 'GET_CLASSES_BY_COURSE_SUCCESS';
export const GET_CLASSES_BY_COURSE_FAILURE = 'GET_CLASSES_BY_COURSE_FAILURE';

// Search class by subject
export const SEARCH_CLASSES_BY_SUBJECT_REQUEST = 'SEARCH_CLASSES_BY_SUBJECT_REQUEST';
export const SEARCH_CLASSES_BY_SUBJECT_SUCCESS = 'SEARCH_CLASSES_BY_SUBJECT_SUCCESS';
export const SEARCH_CLASSES_BY_SUBJECT_FAILURE = 'SEARCH_CLASSES_BY_SUBJECT_FAILURE';

// API add student to class
export const ADD_STUDENT_TO_CLASS_REQUEST = 'ADD_STUDENT_TO_CLASS_REQUEST';
export const ADD_STUDENT_TO_CLASS_SUCCESS = 'ADD_STUDENT_TO_CLASS_SUCCESS';
export const ADD_STUDENT_TO_CLASS_FAILURE = 'ADD_STUDENT_TO_CLASS_FAILURE';

// API get all student in class
export const GET_ALL_STUDENT_IN_CLASS_REQUEST = 'GET_ALL_STUDENT_IN_CLASS_REQUEST';
export const GET_ALL_STUDENT_IN_CLASS_SUCCESS = 'GET_ALL_STUDENT_IN_CLASS_SUCCESS';
export const GET_ALL_STUDENT_IN_CLASS_FAILURE = 'GET_ALL_STUDENT_IN_CLASS_FAILURE';
