
// API get statistical-point
export const GET_STATISTICAL_POINT_REQUEST = 'GET_STATISTICAL_POINT_REQUEST';
export const GET_STATISTICAL_POINT_SUCCESS = 'GET_STATISTICAL_POINT_SUCCESS';
export const GET_STATISTICAL_POINT_FAILURE = 'GET_STATISTICAL_POINT_FAILURE';

// API get statistical-point student
export const GET_STATISTICAL_POINT_STUDENT_REQUEST = 'GET_STATISTICAL_POINT_STUDENT_REQUEST';
export const GET_STATISTICAL_POINT_STUDENT_SUCCESS = 'GET_STATISTICAL_POINT_STUDENT_SUCCESS';
export const GET_STATISTICAL_POINT_STUDENT_FAILURE = 'GET_STATISTICAL_POINT_STUDENT_FAILURE';
