// API get all student in class
export const GET_ALL_STUDENT_REQUEST = 'GET_ALL_STUDENT_REQUEST';
export const GET_ALL_STUDENT_SUCCESS = 'GET_ALL_STUDENT_SUCCESS';
export const GET_ALL_STUDENT_FAILURE = 'GET_ALL_STUDENT_FAILURE';

// API get all classroom
export const GET_ALL_CLASSROOM_REQUEST = 'GET_ALL_CLASSROOM_REQUEST';
export const GET_ALL_CLASSROOM_SUCCESS = 'GET_ALL_CLASSROOM_SUCCESS';
export const GET_ALL_CLASSROOM_FAILURE = 'GET_ALL_CLASSROOM_FAILURE';

// API edit point
export const EDIT_POINT_REQUEST = 'EDIT_POINT_REQUEST';
export const EDIT_POINT_SUCCESS = 'EDIT_POINT_SUCCESS';
export const EDIT_POINT_FAILURE = 'EDIT_POINT_FAILURE';

// API delete point
export const DELETE_POINT_REQUEST = 'DELETE_POINT_REQUEST';
export const DELETE_POINT_SUCCESS = 'DELETE_POINT_SUCCESS';
export const DELETE_POINT_FAILURE = 'DELETE_POINT_FAILURE';