export const GET_STUDENTS_REQUEST = 'GET_STUDENTS_REQUEST';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAILURE = 'GET_STUDENTS_FAILURE';

export const SEARCH_STUDENTS_REQUEST = 'SEARCH_STUDENTS_REQUEST';
export const SEARCH_STUDENTS_SUCCESS = 'SEARCH_STUDENTS_SUCCESS';
export const SEARCH_STUDENTS_FAILURE = 'SEARCH_STUDENTS_FAILURE';

export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAILURE = 'CREATE_STUDENT_FAILURE';

export const EDIT_STUDENT_REQUEST = 'EDIT_STUDENT_REQUEST';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';
export const EDIT_STUDENT_FAILURE = 'EDIT_STUDENT_FAILURE';

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';

export const GET_STUDENT_DETAIL_BY_ID_REQUEST = 'GET_STUDENT_DETAIL_BY_ID_REQUEST';
export const GET_STUDENT_DETAIL_BY_ID_SUCCESS = 'GET_STUDENT_DETAIL_BY_ID_SUCCESS';
export const GET_STUDENT_DETAIL_BY_ID_FAILURE = 'GET_STUDENT_DETAIL_BY_ID_FAILURE';

export const GET_STUDENT_MARK_BY_ID_REQUEST = 'GET_STUDENT_MARK_BY_ID_REQUEST';
export const GET_STUDENT_MARK_BY_ID_SUCCESS = 'GET_STUDENT_MARK_BY_ID_SUCCESS';
export const GET_STUDENT_MARK_BY_ID_FAILURE = 'GET_STUDENT_MARK_BY_ID_FAILURE';

export const GET_STUDENT_ACCUMULATE_POINT_REQUEST = 'GET_STUDENT_ACCUMULATE_POINT_REQUEST';
export const GET_STUDENT_ACCUMULATE_POINT_SUCCESS = 'GET_STUDENT_ACCUMULATE_POINT_SUCCESS';
export const GET_STUDENT_ACCUMULATE_POINT_FAILURE = 'GET_STUDENT_ACCUMULATE_POINT_FAILURE';

export const GET_STUDENT_DETAIL_BY_STUDENT_CODE_REQUEST = 'GET_STUDENT_DETAIL_BY_STUDENT_CODE_REQUEST';
export const GET_STUDENT_DETAIL_BY_STUDENT_CODE_SUCCESS = 'GET_STUDENT_DETAIL_BY_STUDENT_CODE_SUCCESS';
export const GET_STUDENT_DETAIL_BY_STUDENT_CODE_FAILURE = 'GET_STUDENT_DETAIL_BY_STUDENT_CODE_FAILURE';
