// Get subjects
export const GET_SUBJECTS_REQUEST = 'GET_SUBJECTS_REQUEST';
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const GET_SUBJECTS_FAILURE = 'GET_SUBJECTS_FAILURE';

// Get subjects
export const GET_SUBJECT_DETAIL_REQUEST = 'GET_SUBJECT_DETAIL_REQUEST';
export const GET_SUBJECT_DETAIL_SUCCESS = 'GET_SUBJECT_DETAIL_SUCCESS';
export const GET_SUBJECT_DETAIL_FAILURE = 'GET_SUBJECT_DETAIL_FAILURE';


// Create subjects
export const CREATE_SUBJECT_REQUEST = 'CREATE_SUBJECT_REQUEST';
export const CREATE_SUBJECT_SUCCESS = 'CREATE_SUBJECT_SUCCESS';
export const CREATE_SUBJECT_FAILURE = 'CREATE_SUBJECT_FAILURE';

// Edit subjects
export const EDIT_SUBJECT_REQUEST = 'EDIT_SUBJECT_REQUEST';
export const EDIT_SUBJECT_SUCCESS = 'EDIT_SUBJECT_SUCCESS';
export const EDIT_SUBJECT_FAILURE = 'EDIT_SUBJECT_FAILURE';

// Delete subjects
export const DELETE_SUBJECT_REQUEST = 'DELETE_SUBJECT_REQUEST';
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS';
export const DELETE_SUBJECT_FAILURE = 'DELETE_SUBJECT_FAILURE';

// Get list semester
export const GET_LIST_SEMESTER_REQUEST = 'GET_LIST_SEMESTER_REQUEST';
export const GET_LIST_SEMESTER_SUCCESS = 'GET_LIST_SEMESTER_SUCCESS';
export const GET_LIST_SEMESTER_FAILURE = 'GET_LIST_SEMESTER_FAILURE';

// Get subject detail by id
export const GET_SUBJECT_DETAIL_BY_ID_REQUEST = 'GET_SUBJECT_DETAIL_BY_ID_REQUEST';
export const GET_SUBJECT_DETAIL_BY_ID_SUCCESS = 'GET_SUBJECT_DETAIL_BY_ID_SUCCESS';
export const GET_SUBJECT_DETAIL_BY_ID_FAILURE = 'GET_SUBJECT_DETAIL_BY_ID_FAILURE';
