// API get all teacher
export const GET_ALL_TEACHERS_REQUEST = 'GET_ALL_TEACHERS_REQUEST';
export const GET_ALL_TEACHERS_SUCCESS = 'GET_ALL_TEACHERS_SUCCESS';
export const GET_ALL_TEACHERS_FAILURE = 'GET_ALL_TEACHERS_FAILURE';

// API create teacher
export const CREATE_TEACHER_REQUEST = 'CREATE_TEACHER_REQUEST';
export const CREATE_TEACHER_SUCCESS = 'CREATE_TEACHER_SUCCESS';
export const CREATE_TEACHER_FAILURE = 'CREATE_TEACHER_FAILURE';

// API update teacher
export const UPDATE_TEACHER_REQUEST = 'UPDATE_TEACHER_REQUEST';
export const UPDATE_TEACHER_SUCCESS = 'UPDATE_TEACHER_SUCCESS';
export const UPDATE_TEACHER_FAILURE = 'UPDATE_TEACHER_FAILURE';

// API get all my class
export const SEARCH_MY_CLASSES_REQUEST = 'SEARCH_MY_CLASSES_REQUEST';
export const SEARCH_MY_CLASSES_SUCCESS = 'SEARCH_MY_CLASSES_SUCCESS';
export const SEARCH_MY_CLASSES_FAILURE = 'SEARCH_MY_CLASSES_FAILURE';
