// API get column in student
export const GET_STUDENT_COLUMN_REQUEST = 'GET_STUDENT_COLUMN_REQUEST';
export const GET_STUDENT_COLUMN_SUCCESS = 'GET_STUDENT_COLUMN_SUCCESS';
export const GET_STUDENT_COLUMN_FAILURE = 'GET_STUDENT_COLUMN_FAILURE';

// API get column in point
export const GET_POINT_COLUMN_REQUEST = 'GET_POINT_COLUMN_REQUEST';
export const GET_POINT_COLUMN_SUCCESS = 'GET_POINT_COLUMN_SUCCESS';
export const GET_POINT_COLUMN_FAILURE = 'GET_POINT_COLUMN_FAILURE';

// API upload file
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';

// API post mapping column
export const POST_MAPPING_COLUMN_REQUEST = 'POST_MAPPING_COLUMN_REQUEST';
export const POST_MAPPING_COLUMN_SUCCESS = 'POST_MAPPING_COLUMN_SUCCESS';
export const POST_MAPPING_COLUMN_FAILURE = 'POST_MAPPING_COLUMN_FAILURE';

// API get file status list
export const GET_FILE_STATUS_REQUEST = 'GET_FILE_STATUS_REQUEST';
export const GET_FILE_STATUS_SUCCESS = 'GET_FILE_STATUS_SUCCESS';
export const GET_FILE_STATUS_FAILURE = 'GET_FILE_STATUS_FAILURE';

// API download file
export const DOWNLOAD_FILE_REQUEST = 'DOWNLOAD_FILE_REQUEST';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS';
export const DOWNLOAD_FILE_FAILURE = 'DOWNLOAD_FILE_FAILURE';

// API get all documents
export const GET_ALL_DOCUMENTS_REQUEST = 'GET_ALL_DOCUMENTS_REQUEST';
export const GET_ALL_DOCUMENTS_SUCCESS = 'GET_ALL_DOCUMENTS_SUCCESS';
export const GET_ALL_DOCUMENTS_FAILURE = 'GET_ALL_DOCUMENTS_FAILURE';

// API upload document
export const UPLOAD_DOCUMENT_REQUEST = 'UPLOAD_DOCUMENT_REQUEST';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAILURE = 'UPLOAD_DOCUMENT_FAILURE';

// API download document
export const DOWNLOAD_DOCUMENT_REQUEST = 'DOWNLOAD_DOCUMENT_REQUEST';
export const DOWNLOAD_DOCUMENT_SUCCESS = 'DOWNLOAD_DOCUMENT_SUCCESS';
export const DOWNLOAD_DOCUMENT_FAILURE = 'DOWNLOAD_DOCUMENT_FAILURE';