import HttpService from '../utils/http-service';

export const getAllStudent = async () => {
  let response = {
    data: [
      {
        id: 1,
        name: 'Nguyễn Văn A',
        class: 'HD01',
        subject: 'HD01',
        regularScore1: 8,
        regularScore2: 9,
        regularScore3: 10,
        midTermScore1: 8,
        midTermScore2: 9,
        averageRegularScore: 9,
        finalScore: 9,
        finalScoreTL: 9,
      },
      {
        id: 2,
        name: 'Nguyễn Văn B',
        class: 'HD02',
        subject: 'HD02',
        regularScore1: 8,
        regularScore2: 9,
        regularScore3: 10,
        midTermScore1: 8,
        midTermScore2: 9,
        averageRegularScore: 9,
        finalScore: 9,
        finalScoreTL: 9,
      },
      {
        id: 3,
        name: 'Nguyễn Văn C',
        class: 'HD03',
        subject: 'HD03',
        regularScore1: 8,
        regularScore2: 9,
        regularScore3: 10,
        midTermScore1: 8,
        midTermScore2: 9,
        averageRegularScore: 9,
        finalScore: 9,
        finalScoreTL: 9,
      },
      {
        id: 4,
        name: 'Nguyễn Văn D',
        class: 'HD04',
        subject: 'HD04',
        regularScore1: 8,
        regularScore2: 9,
        regularScore3: 10,
        midTermScore1: 8,
        midTermScore2: 9,
        averageRegularScore: 9,
        finalScore: 9,
        finalScoreTL: 9,
      },
      {
        id: 5,
        name: 'Nguyễn Văn E',
        class: 'HD05',
        subject: 'HD05',
        regularScore1: 8,
        regularScore2: 9,
        regularScore3: 10,
        midTermScore1: 8,
        midTermScore2: 9,
        averageRegularScore: 9,
        finalScore: 9,
        finalScoreTL: 9,
      },
      {
        id: 6,
        name: 'Nguyễn Văn F',
        class: 'HD06',
        subject: 'HD06',
        regularScore1: 8,
        regularScore2: 9,
        regularScore3: 10,
        midTermScore1: 8,
        midTermScore2: 9,
        averageRegularScore: 9,
        finalScore: 9,
        finalScoreTL: 9,
      },
      {
        id: 7,
        name: 'Nguyễn Văn G',
        class: 'HD07',
        subject: 'HD07',
        regularScore1: 8,
        regularScore2: 9,
        regularScore3: 10,
        midTermScore1: 8,
        midTermScore2: 9,
        averageRegularScore: 9,
        finalScore: 9,
        finalScoreTL: 9,
      },
      {
        id: 8,
        name: 'Nguyễn Văn H',
        class: 'HD08',
        subject: 'HD08',
        regularScore1: 8,
        regularScore2: 9,
        regularScore3: 10,
        midTermScore1: 8,
        midTermScore2: 9,
        averageRegularScore: 9,
        finalScore: 9,
        finalScoreTL: 9,
      },
      {
        id: 9,
        name: 'Nguyễn Văn I',
        class: 'HD09',
        subject: 'HD09',
        regularScore1: 8,
        regularScore2: 9,
        regularScore3: 10,
        midTermScore1: 8,
        midTermScore2: 9,
        averageRegularScore: 9,
        finalScore: 9,
        finalScoreTL: 9,
      },
      {
        id: 10,
        name: 'Nguyễn Văn K',
        class: 'HD10',
        subject: 'HD10',
        regularScore1: 8,
        regularScore2: 9,
        regularScore3: 10,
        midTermScore1: 8,
        midTermScore2: 9,
        averageRegularScore: 9,
        finalScore: 9,
        finalScoreTL: 9,
      },
    ],
  };
  return response.data;
};
